### ISSUE TITLE
What does due process mean

### ISSUE THREAD

**Issue by ekr** [patcg/patwg-charter#11]
The current text says: "This Working Group will seek to make decisions through consensus and due process, ". This comes from the W3C document, but it seems unclear what it actually means?

**Comment by martinthomson** [comment]
Is https://www.w3.org/2021/Process-20211102/#decisions sufficient as a reference?

**Comment by AramZS** [comment]
@ekr @martinthomson let me know if adding the link feels sufficient to you?

**Comment by ekr** [comment]
I suppose. It's a strange word to use in this context.
