### ISSUE TITLE
jwrosewell: voting

### ISSUE THREAD

**Issue by ekr** [patcg/patwg-charter#12]
Note: I am transcribing comments from the gdoc to issues.

@jwrosewell suggests:

1. An option for anonymous voting
2. Deleting the text that says "and includes no voting procedures beyond what the Process Document requires".

**Comment by ekr** [comment]
I think these are paired because the Process Document does not have anonymous voting, but I could be wrong.

**Comment by jwrosewell** [comment]
@ekr Thank you. The proposed amendment is to enable anonymous input to decision making due to the heightened fear of retaliation in relation to the subjects of advertising and privacy, inability to contribute publicly due to affiliated organisation policy, and lack of time to engage but still wanting a voice. The latter point is not related to anonymous voting but would lend itself to a vote much like those that the W3C use for charter adoption.

**Comment by jwrosewell** [comment]
In which case how do we assess the views of a wider group of participants than the direct members of the group and ensure their views are considered?

**Comment by ekr** [comment]
I think this is a reasonable question and one that I've seen other groups grapple with. Ultimately, however, the decision making body for W3C is the membership and so while it's important that the WG hear from other stakeholders, the way that turns into input into the W3C decisionmaking process is by member votes and then ultimately by the Director  processing FOs, when he can consider any inputs he wants.

**Comment by darobin** [comment]
A document is open for review the moment it hits FPWD and groups are required to address _substantive_ issues raised by anyone. Such broad review and the public accountability that goes with are key to the legitimacy of existing documents published by groups and the TAG. Evidently, "substantive" requires that the comment be actionable, technical, not reopen previous discussion, etc.

**Comment by AramZS** [comment]
In terms of how to assess the wider group of participants and acknowledging that stakeholders of this process may have substantive issues that they do not know how to raise via GitHub issues or will have trouble phrasing technically, I think this problem can be resolved via the mechanism I've proposed at https://github.com/patcg/patwg-charter/pull/14 where documents, at each major step in the WG, can leverage the CG to request feedback from non-W3C members (willing to agree to the CG's terms of course)  within a specific process and time. We should refine that process if the concern is assuring that the widest possible set of relevant stakeholders is included. 

@jwrosewell I assume that an organizational-level vote is not what you are looking for here and it is clear that anonymous individual voting is both not a practice in the W3C and counterproductive to your stated concerns considering the potential vote stuffing issue? If we can agree on that I don't think any more progress can be made on this issue and I would like to close it. 

If you feel strongly that an organizational-level vote is the way decision making should be done then that would best be discussed on a separate issue.

**Comment by jwrosewell** [comment]
Happy to close this issue and incorporate the theme into #13.

I will continue to progress anonymous voting at W3C level.

**Comment by AramZS** [comment]
Thanks @jwrosewell - I will close here.
