### ISSUE TITLE
Require Data Section in Success Criteria

### ISSUE THREAD

**Issue by bmayd** [patcg/patwg-charter#35]
The Success Criteria in the working group charter says that: 

> ​​Each normative specification should contain separate sections detailing all known security and privacy implications for implementers, Web authors, and end users.

I'd like to suggest that we add  a data section.

The notion of privacy can’t be separated from data, which suggests there can be no meaningful assessment of privacy without identification of the data in question. While I agree that defining privacy is not something we should pursue further, I do think the question of identifying the data inputs and outputs of features is something we haven't focused on and which we ought to give thought to. 

More specifically, I think we should consider requiring that specifications include a separate section detailing what data inputs a feature requires and what outputs it provides, potentially along with associated attributes, like a notion of how identifying the data is, whether its use should be consented and user controls offered and what the consequences of users exercising controls are for the feature.

**Comment by AramZS** [comment]
That might be unnecessary language for what would presumably already be done, but by shape, I meant data format (type, object properties, anticipated size, etc). In retrospect I think I can probably remove that clause.

**Comment by bmayd** [comment]
Thanks for clarifying and I agree with leaving it out; I think "...detail anticipated data..." captures it.

**Comment by AramZS** [comment]
Hey @bmayd - my hope is that this is resolved by https://github.com/patcg/patwg-charter/pull/59 and we can discuss the above changes as a separate PR only if that PR is objected to.

**Comment by bmayd** [comment]
What is stated in [#59](https://github.com/patcg/patwg-charter/pull/59) addresses my concerns and is sufficient for the WG charter.

**Comment by AramZS** [comment]
I think we've got this addressed in the latest set of changes now. Closing this issue.
