### ISSUE TITLE
Extend timeframe to late September to cater for holidays

### ISSUE THREAD

**Issue by jwrosewell** [patcg/patwg-charter#38]
Many people in Europe enjoy holidays from mid July to the end of August. This makes gaining organizational agreement on important matters more complex as the required people are not available at the same time. To enable maximum considered input any time period should be extended to late September 2022.

**Comment by jwrosewell** [comment]
The issue relates to the time period that the W3C will provide the AC to review the charter.

The charter as drafted today does not comply with the [W3C antitrust guidelines](https://www.w3.org/Consortium/Legal/2017/antitrust-guidance) let alone external laws concerning competition. This has been touched on in #30 and elsewhere. Should the W3C Team allow the charter to advance unaltered then progression to the AC during a period where many members and colleagues are on holiday will inhibit proper review of the charter on this critical matter.

As background to at least part of the Formal Objection my organisation will raise if the charter as draft were advanced.

The guidelines state (emphasis added);

> "W3C does not play any role in the competitive decisions of W3C participants **nor in any way restrict competition**."

If this WG charter limits the scope of the group to "new web platform features [in the field of advertising technologies] intended to be implemented in browsers or similar user agents" then competition in the field of advertising technologies is being restricted by the group. 

This is not a new field; it is a well established field where individual participants are worth in excess of 1.5 trillion USD, where the economic model for critical services for society is dependent on advertising technologies. It is not the same as a similar group chartered 20 years ago, or one being chartered today to explore some new emerging field that is yet to mature.

**Comment by AramZS** [comment]
It is now mid-September so I assume that this is fully resolved one way or another.
