### ISSUE TITLE
WG Charter Comment Resolution

### ISSUE THREAD

**Issue by AramZS** [patcg/patwg-charter#44]
The draft Private Advertising Technology Working Group (PATWG) charter was out for review over the summer. We now need to address the comments and formal objections received during that review process. The chairs will use the GitHub issues / pull requests to document the comments / formal objections; we will generate pull requests to address those issues where the change was clear. The CG can discuss them and then we as chairs can judge consensus.

Stay tuned for issues / pull requests[^1].

There are few things we would like to note about the process:

1. The CG is dealing with these comments because the CG generated the charter text.
2. There were comments that are in direct conflict with others. Therefore, it is impossible to address all the comments to everyone’s satisfaction. Please remember we are using the consensus process and consensus is more about whether you can live with the outcome than getting everything your way.
3. There is more process after the CG consensus is judged and changes are incorporated. For example, those that still have formal objections after the WG charter has been amended based on CG consensus can continue to hold those formal objections in later stages of the WG chartering process.
4. We will label these issues and PRs as ‘comment-response’ to make it clear that we are attempting to realize the objections by different parties and that these PRs and issues do not necessarily represent the options or positions of the chairs. 

[^1]: Mozilla has already submitted a PR to address their formal objections. Instead of re-writing that one, we will just adopt it as our own.

**Comment by AramZS** [comment]
Noting that more PRs and issues will come later as we work on them.

**Comment by samuelweiler** [comment]
Per discussion [today](https://github.com/patcg/meetings/tree/main/2023/05/02-telecon), close this?
