### ISSUE TITLE
jwrosewell: "web features" -> "solutions"

### ISSUE THREAD

**Issue by ekr** [patcg/patwg-charter#5]
Note: I am moving gdoc comments into this repo.

@jwrosewell suggests that instead of specifying that the charter produces "web features" or "APIs" it should say "solutions"

**Comment by jwrosewell** [comment]
This would ensure we focus on outcomes.

**Comment by AramZS** [comment]
Charters should define specific meaningful documents that it will generate. For a Working Group under the W3C it is generally considered that the outcomes a Working Group will create are specifically in the form of Web Features and APIs in the form of those specific documents. Working Groups rely on a framework of supporting procedures in the W3C specifically to generate such documents and that's how they are generally designed to function. The outcomes we wish to focus on are these specific types of documents so this change would, I think, make it less accurate not more accurate in describing the WG's focus.

**Comment by AramZS** [comment]
Seeing #8 I believe resolves this question of broad scope changes requested, and the lack of support for them. As such, I believe this request has been deeply considered and resolved under our standards of consensus.
