### ISSUE TITLE
Charter should include baseline privacy boundaries 

### ISSUE THREAD

**Issue by ShivanKaul** [patcg/patwg-charter#61]
For this group to be successful, it needs to have a very clear definition of what the minimum privacy goals and boundaries are, and the charter currently lacks this.

The charter currently says:

>The purpose of these features is to support web advertising without compromising user privacy. Here “privacy” minimally refers to appropriate processing of personal information. Ways in which new features might enable inappropriate processing include (but are not limited to) enabling of cross-site or cross context recognition of users or enabling same-site or same-context recognition of users across the clearing of state.

The goal of this group is to produce specs that enable web advertising (easy) without compromising privacy (hard). Without the privacy bit, the advertising use-cases are straightforward. So for this group to be meaningfully deliver on its stated goal, we need to be explicit about what exactly we mean by the "privacy" constraint. To be clear, I'm not suggesting that we try to put down every single privacy risk that could ever arise - some of those will arise once the proposals start taking more shape. But we need a minimum baseline of privacy boundaries that will not be violated by any spec that we work on, and right now we don't have it. This baseline cannot be defined post facto, once we already have a technical solution that we like. Otherwise, we seriously risk overfitting the privacy and security boundaries around whatever spec we work on and decide to ship.

**Comment by seanturner** [comment]
I think this was somewhat motivated by the discussion we had in May about #59.  Check out the minutes in the WG charter review portion: https://github.com/patcg/meetings/tree/main/2023/05/02-telecon.

**Comment by benjaminsavage** [comment]
I'd like to state my opinion on this issue.

I think the charter already *does* have a minimum bar - right there in the part you highlighted @ShivanKaul. The minimum bar is not making cross-site linkage, or same-site recognition across state clearing possible.

As we discussed today, there will be _additional_, specific privacy threats we need to guard against in the context of various proposals. These will *definitely* be discussed in the working group - but need not be a part of the WG charter itself.

**Comment by csharrison** [comment]
Note there were public comments on this issue in our current F2F session. Minutes link here:
https://docs.google.com/document/d/1raFJmEEobFzXj7VPC0GRXKtL_pxfR-5Mi6YJwtHalYg/edit#bookmark=id.g3aze6uw1y5

**Comment by AramZS** [comment]
Hi, we're not seeing support in the group to keep this issue open, as per comments in the meeting and above. If people would like to further support this issue, now is the time to speak up otherwise we will consider closing it.

**Comment by pes10k** [comment]
@AramZS

I +1'ed this issue when doing the horizontal review of the charter (see https://github.com/w3c/strategy/issues/222#issuecomment-1579485152). Given the history of the privacy concerns around Web advertising, I strongly urge the group to find someway of saying more positively what privacy boundaries the group aims to work within.

Currently the text states two things the group won't do (no cross-site or cross context recognition, no same-site re-identification across storage clears). Thats great, but there are an enormous number of dimensions in privacy work, and so I think the charter needs to be more specific about privacy, consent and information flow limits the group plans to work within.

I appreciate that coming up with a full and unambiguous definition of what privacy means is difficult and beyond whats generally necessary for a charter. I'm not requesting anything like that. But I think at least *some* more specificity is necessary about what the WG considers in-and-out of scope privacy-wise

**Comment by AramZS** [comment]
The group has determined it's privacy definition within the charter for this specific work is sufficient.
